name: dr
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 8.1.0+21

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collapsible_sidebar:
    path: packages/collapsible_sidebar/
  dynamic_theme:
    path: packages/dynamic_theme/
  quill_delta_viewer:
    path: packages/quill_delta_viewer/
  responsive_scaffold:
    path: packages/responsive_scaffold/
  built_redux:
    path: ../built_redux
  charts_flutter:
    git:
      url: https://github.com/miDeb/charts.git
      path: charts_flutter/
      ref: select_nearest
  flutter_built_redux:
    path: ../flutter_built_redux
  badges:
    git:
      url: https://github.com/miDeb/flutter_badges.git
      ref: nnbd
  biometric_storage:
    git:
      url: https://github.com/miDeb/biometric_storage.git
      ref: nnbd
  built_value: ^8.0.0
  cookie_jar: ^1.0.1
  deleteable_tile: ^0.0.1-nullsafety.1
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  flutter_colorpicker: ^0.4.0-nullsafety.0
  flutter_secure_storage: any
  flutter_typeahead: ^3.0.0-nullsafety.0
  flutter_widget_from_html_core: ^0.3.2+1
  hive: ^1.6.0-nullsafety.2
  http: ^0.12.2
  intl: ^0.17.0-nullsafety.2
  mutex: ^2.0.0-nullsafety.0
  open_file: any
  package_info: ^0.5.0-nullsafety
  path_provider: ^2.0.0-nullsafety
  quill_delta:
    git:
      url: https://github.com/miDeb/quill-delta-dart.git
      ref: nnbd
  scroll_to_index:
    git:
      url: https://github.com/miDeb/scroll-to-index.git
      ref: nnbd
  tuple: ^2.0.0-nullsafety.0
  uni_links: any
  url_launcher: ^6.0.0-nullsafety.6
  collection: ^1.15.0-nullsafety.4
dependency_overrides:
  glob: ^2.0.0-nullsafety.0
  analyzer: ^1.0.0
  intl: ">=0.17.0-nullsafety.2 <= 0.17.0-nullsafety.2"
  quiver: ^3.0.0-nullsafety.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
    git:
      url: https://github.com/dart-lang/build
      ref: master
      path: build_runner/
  built_value_generator: ^8.0.0
  lint: ^1.5.1
  matcher: ^0.12.10-nullsafety.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/index.png"

flutter_native_splash:
  color: "fafafa"
  color_dark: "303030"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
