name: digitales-register
version: 0.1.0
summary: Digitales Register
description: Client für https://digitalesregister.it

confinement: strict
base: core18
grade: stable

apps:
  dr:
    command: dr
    extensions: [flutter-beta] # Where "master" defines which Flutter channel to use for the build
    plugs:
      - network

parts:
  dr:
    override-pull: |
     set -eux
     test -e $SNAPCRAFT_PROJECT_DIR/build && rm -rf $SNAPCRAFT_PROJECT_DIR/build
     snapcraftctl pull
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    build-packages:
      - libsecret-1-dev
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-dev
