on: [push]
  #push:
  #  branches:
  #    - main
  #  paths-ignore:
  #    - "README.md"
  #workflow_dispatch:
  #release:
  #  types:
  #    - created
  #    - edited

jobs:
  
  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@master
        with:
          channel: beta

      - name: Install linux app dependencies
        run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev dpkg-dev pkg-config

      - name: Enable desktop support
        run: flutter config --enable-linux-desktop

      - name: Build Flutter app
        run: flutter build linux -v

      - name: Build Tarball
        run: |
          cp -fr build/linux/x64/release/bundle linux/packaging/usr/bin
          mkdir -p AppDir/
          cp -r linux/packaging/usr AppDir/
          ln -sr AppDir/usr/bin/flutube AppDir/flutube
          tar czf flutube-linux-x86_64.tar.gz -C AppDir/ .
      - uses: svenstaro/upload-release-action@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./flutube-linux-x86_64*
          file_glob: true
          prerelease: ${{ github.event_name != 'release' }}
          release_name: ${{ github.event_name == 'release' && github.event.release.name || 'Development Build' }}
          tag: ${{ github.event_name == 'release' && github.event.release.tag_name || 'continuous' }}
          overwrite: true